package mocks

import "github.com/stretchr/testify/mock"

import "github.com/Bplotka/oidc"

// TokenCache is an autogenerated mock type for the TokenCache type
type TokenCache struct {
	mock.Mock
}

// SetToken provides a mock function with given fields: token
func (_m *TokenCache) SetToken(token *oidc.Token) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*oidc.Token) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Token provides a mock function with given fields:
func (_m *TokenCache) Token() (*oidc.Token, error) {
	ret := _m.Called()

	var r0 *oidc.Token
	if rf, ok := ret.Get(0).(func() *oidc.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oidc.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
