package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import oidc "github.com/bwplotka/oidc"

// TokenSource is an autogenerated mock type for the TokenSource type
type TokenSource struct {
	mock.Mock
}

// OIDCToken provides a mock function with given fields: _a0
func (_m *TokenSource) OIDCToken(_a0 context.Context) (*oidc.Token, error) {
	ret := _m.Called(_a0)

	var r0 *oidc.Token
	if rf, ok := ret.Get(0).(func(context.Context) *oidc.Token); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oidc.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Verifier provides a mock function with given fields:
func (_m *TokenSource) Verifier() oidc.Verifier {
	ret := _m.Called()

	var r0 oidc.Verifier
	if rf, ok := ret.Get(0).(func() oidc.Verifier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oidc.Verifier)
		}
	}

	return r0
}
